Bugfixes for 2 open issues
lutaml/lutaml-uml pull request #100
Opened 2022-10-05 21:19 UTC by martinpwagner

2022-10-27 01:53 UTC, ronaldtse commented
Thank you very much @martinpwagner !

2023-02-21 06:54 UTC, ronaldtse commented
@merceroncode thank you for the contribution -- the Windows builds are failing -- could you help fix them? Thanks.

2023-02-21 18:17 UTC, merceroncode commented
@ronaldtse Pushed out changes for windows.yml, old log is gone now :(

Changed ruby vers to 2.7 and 3.1 for workflows

2023-02-21 21:55 UTC, webdev778 commented on lib/lutaml/uml/parsers/dsl_preprocessor.rb
> +          has_comment = line.match(Regexp.new("//(.)*"))
I would write

```ruby
%r{//.*}
```

instead of

```ruby
Regexp.new("//(.)*")

2023-02-21 21:55 UTC, webdev778 commented on lib/lutaml/uml/parsers/dsl_preprocessor.rb
> +          line.gsub(Regexp.new("//(.)*"), "")
ditto

2023-02-27 17:16 UTC, merceroncode commented
I'm working a full day tomorrow too btw so I'll have time to look into that

2023-03-03 18:31 UTC, ronaldtse requested changes
Can you also incorporate the changes as done in https://github.com/lutaml/lutaml-express/pull/14 ? Thanks.

2023-03-03 18:31 UTC, ronaldtse commented on .github/workflows/macos.yml
> +        ruby: [ '2.7', '3.1' ]
Need to add 3.0

2023-03-03 18:31 UTC, ronaldtse commented on .github/workflows/ubuntu.yml
> +        ruby: [ '3.1' ]
Add 3.0 please

2023-03-03 18:31 UTC, ronaldtse commented on .github/workflows/windows.yml
> +        ruby: [ '2.7', '3.1' ]
Add 3.0 please.

2023-03-09 16:05 UTC, ronaldtse approved these changes

2023-03-09 16:06 UTC, ronaldtse commented
Ping @merceroncode : some failure with Ruby 3.1 and 3.2.

2023-03-09 22:59 UTC, ronaldtse approved these changes

2023-03-15 01:47 UTC, ronaldtse commented
Merging this for additional fixes.

2023-03-15 01:48 UTC, merged